create table users
(
    id       bigint generated by default as identity,
    password varchar(255) not null,
    email    varchar(100) not null,
    name     varchar(50)  not null,
    status   enum('Y','N') not null,
    primary key (id)
)